// Generated by CoffeeScript 1.10.0
(function() {
  var hasProp = {}.hasOwnProperty;

  exports.window = {};

  exports.localStorage = {};

  exports.chrome = {
    runtime: {
      getManifest: function() {
        return {
          version: "1.2.3"
        };
      },
      onConnect: {
        addListener: function() {
          return true;
        }
      },
      onMessage: {
        addListener: function() {
          return true;
        }
      },
      onInstalled: {
        addListener: function() {}
      }
    },
    tabs: {
      onSelectionChanged: {
        addListener: function() {
          return true;
        }
      },
      onUpdated: {
        addListener: function() {
          return true;
        }
      },
      onAttached: {
        addListener: function() {
          return true;
        }
      },
      onMoved: {
        addListener: function() {
          return true;
        }
      },
      onRemoved: {
        addListener: function() {
          return true;
        }
      },
      onActiveChanged: {
        addListener: function() {
          return true;
        }
      },
      onActivated: {
        addListener: function() {
          return true;
        }
      },
      onReplaced: {
        addListener: function() {
          return true;
        }
      },
      query: function() {
        return true;
      }
    },
    windows: {
      onRemoved: {
        addListener: function() {
          return true;
        }
      },
      getAll: function() {
        return true;
      }
    },
    browserAction: {
      setBadgeBackgroundColor: function() {}
    },
    storage: {
      local: {
        get: function() {},
        set: function() {},
        remove: function() {}
      },
      onChanged: {
        addListener: function(func) {
          return this.func = func;
        },
        call: function(key, value) {
          var key_value;
          chrome.runtime.lastError = void 0;
          key_value = {};
          key_value[key] = {
            newValue: value
          };
          if (this.func) {
            return this.func(key_value, 'synced storage stub');
          }
        },
        callEmpty: function(key) {
          var items;
          chrome.runtime.lastError = void 0;
          if (this.func) {
            items = {};
            items[key] = {};
            return this.func(items, 'synced storage stub');
          }
        }
      },
      session: {
        MAX_SESSION_RESULTS: 25
      },
      sync: {
        store: {},
        set: function(items, callback) {
          var key, results, value;
          chrome.runtime.lastError = void 0;
          for (key in items) {
            if (!hasProp.call(items, key)) continue;
            value = items[key];
            this.store[key] = value;
          }
          if (callback) {
            callback();
          }
          results = [];
          for (key in items) {
            if (!hasProp.call(items, key)) continue;
            value = items[key];
            results.push(global.chrome.storage.onChanged.call(key, value));
          }
          return results;
        },
        get: function(keys, callback) {
          var i, items, key, len, ref, value;
          chrome.runtime.lastError = void 0;
          if (keys === null) {
            keys = [];
            ref = this.store;
            for (key in ref) {
              if (!hasProp.call(ref, key)) continue;
              value = ref[key];
              keys.push(key);
            }
          }
          items = {};
          for (i = 0, len = keys.length; i < len; i++) {
            key = keys[i];
            items[key] = this.store[key];
          }
          if (callback) {
            return callback(items);
          }
        },
        remove: function(key, callback) {
          chrome.runtime.lastError = void 0;
          if (key in this.store) {
            delete this.store[key];
          }
          if (callback) {
            callback();
          }
          return global.chrome.storage.onChanged.callEmpty(key);
        }
      }
    }
  };

}).call(this);
