// Generated by CoffeeScript 1.9.1
(function() {
  var popup, ts;

  ts = new TabShepherd(chrome, window.alert);

  popup = angular.module('TabShepPopup', []);

  popup.config(function($locationProvider) {
    return $locationProvider.html5Mode(true);
  });

  popup.controller('HelpController', function($scope, $location) {
    var cmd, par;
    par = $location.search().command;
    cmd = ts.getCommand(par);
    if (par) {
      $scope.command = par;
      $scope.desc = cmd.desc;
      return $scope.examples = cmd.examples;
    }
  });

}).call(this);
