// Generated by CoffeeScript 1.9.1
(function() {
  var popup, ts,
    hasProp = {}.hasOwnProperty;

  ts = new TabShepherd(chrome, window.alert);

  popup = angular.module('HelpPopup', []);

  popup.config(function($locationProvider) {
    return $locationProvider.html5Mode({
      enabled: true,
      requireBase: false
    });
  });

  popup.controller('HelpController', function($scope, $location) {
    var cmd, name, ref;
    $scope.categories = {
      'Moving tabs': {},
      'Changing focus': {},
      'Managing window definitions': {},
      'Managing URL patterns': {},
      'Informational': {}
    };
    ref = ts.getCommands();
    for (name in ref) {
      if (!hasProp.call(ref, name)) continue;
      cmd = ref[name];
      if ($scope.categories[cmd.type] != null) {
        $scope.categories[cmd.type][name] = cmd;
      }
    }
    return $scope.selected = $location.search().command;
  });

}).call(this);
