// Generated by CoffeeScript 1.9.1
(function() {
  var popup, ts;

  ts = new TabShepherd(chrome, window.alert);

  popup = angular.module('TabShepPopup', []);

  popup.controller('PopupController', function($scope) {
    ts.withCurrentWindow(function(win) {
      var ref, ref1;
      $scope.name = (ref = ts.getName(win)) != null ? ref : '';
      if ($scope.name) {
        $scope.def = ts.getDefinition($scope.name);
        if (($scope.def != null) && ($scope.def.patterns == null)) {
          $scope.def.patterns = [];
        }
        if (((ref1 = $scope.def) != null ? ref1.patterns : void 0) != null) {
          console.dir($scope.def.patterns);
        }
      }
      return $scope.$digest();
    });
    $scope.setName = function() {
      return ts.withCurrentWindow(function(win) {
        ts.setName(win, $scope.name);
        return ts.storeDefinitions();
      });
    };
    return $scope.addPattern = function() {
      $scope.def.patterns.push($scope.newPattern);
      return ts.withCurrentWindow(function(win) {
        ts.assignPattern(win, $scope.newPattern);
        $scope.newPattern = '';
        return ts.storeDefinitions();
      });
    };
  });

}).call(this);
