// Generated by CoffeeScript 1.9.1
(function() {
  var popup, ts;

  ts = new TabShepherd(chrome, window.alert);

  popup = angular.module('TabShepPopup', []);

  popup.controller('PopupController', function($scope) {
    return ts.withCurrentWindow(function(win) {
      var ref;
      $scope.name = (ref = ts.getName(win)) != null ? ref : 'none';
      if ($scope.name) {
        $scope.def = ts.getDefinition($scope.name);
      }
      if ($scope.def.patterns == null) {
        $scope.def.patterns = [];
      }
      console.dir($scope.def.patterns);
      $scope.setName = function() {
        return ts.withCurrentWindow(function(win) {
          ts.setName(win, $scope.name);
          return ts.storeDefinitions();
        });
      };
      return $scope.addPattern = function() {
        $scope.def.patterns.push($scope.newPattern);
        return ts.withCurrentWindow(function(win) {
          ts.assignPattern($scope.newPattern, win);
          $scope.newPattern = '';
          return ts.storeDefinitions();
        });
      };
    });
  });

}).call(this);
