// Generated by CoffeeScript 1.9.1
(function() {
  var TabShepherd, _, activeTabId, alert, alertText, assertAlert, assertFocus, assertNoOutput, assertOmni, assertText, changeInput, chrome, createTab, defs, enterInput, expectNoResponseFor, expectResponseFor, expectSuggestionFor, focusedTabIds, focusedWindowId, inputChanged, inputEntered, omniboxText, randomId, reset, suggest, tabValues, tabs, ts, windowRemovedListener, windows, withSavedDef,
    hasProp = {}.hasOwnProperty;

  require("./shoulda.js");

  _ = require("./underscore-min.js");

  global.extend = function(hash1, hash2) {
    var key;
    for (key in hash2) {
      hash1[key] = hash2[key];
    }
    hash1;
    return extend(global, require("./chromeStubs.js"));
  };

  TabShepherd = require("./TabShepherd.js").TabShepherd;

  inputChanged = null;

  inputEntered = null;

  windowRemovedListener = null;

  activeTabId = null;

  windows = null;

  focusedWindowId = 1;

  focusedTabIds = {};

  tabs = null;

  defs = null;

  omniboxText = null;

  alertText = null;

  ts = null;

  chrome = null;

  tabValues = function() {
    return _.values(tabs);
  };

  withSavedDef = function(name, callback) {
    return chrome.storage.local.get('windowDefs', function(data) {
      return callback(data['windowDefs'][name]);
    });
  };

  suggest = function(text) {
    return omniboxText = text[0].description;
  };

  alert = function(text) {
    return alertText = text;
  };

  randomId = function() {
    return Math.floor(Math.random() * 10000);
  };

  createTab = function(id, windowId, url) {
    var tab;
    tab = {
      id: id,
      windowId: windowId,
      url: url
    };
    tabs[id] = tab;
    return tab;
  };

  reset = function() {
    tabs = {
      3: {
        id: 3,
        windowId: 1,
        url: 'http://sweetthings.com',
        title: ''
      },
      4: {
        id: 4,
        windowId: 1,
        url: 'http://reallybitterthings.com',
        title: ''
      },
      5: {
        id: 5,
        windowId: 2,
        url: 'http://sourthings.com',
        title: ''
      },
      6: {
        id: 6,
        windowId: 2,
        url: 'http://salty.com',
        title: ''
      }
    };
    defs = {
      goodbye: {
        name: 'goodbye',
        patterns: ['blue'],
        activeUrl: 'http://sourthings.com'
      }
    };
    focusedWindowId = 1;
    windows = {
      1: {
        id: 1,
        tabs: [tabs[3], tabs[4]],
        activeTabId: 4,
        name: 'hello'
      },
      2: {
        id: 2,
        tabs: [tabs[5], tabs[6]],
        activeTabId: 5
      }
    };
    chrome = {
      runtime: {
        lastError: null
      },
      storage: {
        local: {
          get: function(name, cb) {
            var res;
            res = {};
            if (name === 'windowDefs') {
              res[name] = defs;
            }
            return cb(res);
          },
          set: function(newDefs, cb) {
            defs = newDefs['windowDefs'];
            return cb();
          }
        }
      },
      omnibox: {
        onInputChanged: {
          addListener: function(listener) {
            return inputChanged = listener;
          }
        },
        onInputEntered: {
          addListener: function(listener) {
            return inputEntered = listener;
          }
        }
      },
      windows: {
        onRemoved: {
          addListener: function(listener) {
            return windowRemovedListener = listener;
          }
        },
        getCurrent: function(o, cb) {
          if ((focusedWindowId == null) || (windows[focusedWindowId] == null)) {
            throw 'No current window defined';
          }
          return cb(windows[focusedWindowId]);
        },
        create: function(ops, cb) {
          var tab, win, winId;
          winId = randomId();
          win = {
            id: winId,
            tabs: []
          };
          tab = createTab(randomId(), winId, '');
          win.tabs.push(tab);
          win.activeTabId = tab.id;
          windows[winId] = win;
          focusedWindowId = winId;
          return cb(win);
        },
        get: function(id, ops, cb) {
          return cb(windows[id]);
        },
        getAll: function(ops, cb) {
          var k, v;
          return cb((function() {
            var results;
            results = [];
            for (k in windows) {
              if (!hasProp.call(windows, k)) continue;
              v = windows[k];
              results.push(v);
            }
            return results;
          })());
        },
        update: function(winId, ops, cb) {
          if (ops != null ? ops.focused : void 0) {
            focusedWindowId = winId;
          }
          return cb();
        }
      },
      tabs: {
        create: function(winId, url, cb) {
          var tab, tabId;
          tabId = randomId();
          tab = createTab(tabId, winId, url);
          windows[winId].tabs.push(tab);
          return cb(tab);
        },
        query: function(ops, cb) {
          var fits, id, tab;
          fits = function(t) {
            var res;
            res = true;
            if (ops.windowId != null) {
              res = res && t.windowId === ops.windowId;
            }
            if (ops.active) {
              res = res && windows[t.windowId].activeTabId === t.id;
            }
            return res;
          };
          return cb((function() {
            var results;
            results = [];
            for (id in tabs) {
              if (!hasProp.call(tabs, id)) continue;
              tab = tabs[id];
              if (fits(tab)) {
                results.push(tab);
              }
            }
            return results;
          })());
        },
        get: function(id, cb) {
          return cb(tabs[id]);
        },
        getAllInWindow: function(winId, cb) {
          return cb(_.filter(tabValues(), function(t) {
            return t.windowId === winId;
          }));
        },
        update: function(id, ops, cb) {
          var k, tab, v;
          tab = tabs[id];
          for (k in ops) {
            if (!hasProp.call(ops, k)) continue;
            v = ops[k];
            if (k === 'active') {
              windows[tab.windowId].activeTabId = tab.id;
            } else {
              tab[k] = v;
            }
          }
          return cb(tab);
        },
        move: function(ids, ops, cb) {
          var i, id, idx, len, newWin, tab, win;
          newWin = windows[ops.windowId];
          for (i = 0, len = ids.length; i < len; i++) {
            id = ids[i];
            win = windows[tab.windowId];
            idx = _.findIndexOf(win.tabs, function(t) {
              return t.id === id;
            });
            win.tabs.splice(idx, 1);
            tab = tabs[id];
            newWin.tabs.push(tab);
          }
          return cb();
        },
        remove: function(id, cb) {
          var idx, tab, win;
          tab = tabs[id];
          win = windows[tab.windowId];
          idx = _.findIndexOf(win.tabs, function(t) {
            return t.id === id;
          });
          win.tabs.splice(idx, 1);
          delete tabs[id];
          return cb();
        }
      }
    };
    return ts = new TabShepherd(chrome, alert);
  };

  changeInput = function(input) {
    return inputChanged(input, suggest);
  };

  enterInput = function(input) {
    return inputEntered(input);
  };

  assertOmni = function(text) {
    return assertText(text, omniboxText);
  };

  assertAlert = function(text) {
    return assertText(text, alertText);
  };

  assertNoOutput = function() {
    if (omniboxText !== null) {
      assert.fail("Expected no omniboxText, got '" + omniboxText + "'");
    }
    if (alertText !== null) {
      return assert.fail("Expected no alertText, got '" + alertText + "'");
    }
  };

  assertText = function(text, holder) {
    var out;
    out = (function() {
      if (typeof text === 'object' && typeof text.test === 'function') {
        if (!new RegExp(text).test(holder)) {
          return assert.fail("No match for " + text + " in " + holder);
        }
      } else if (typeof text === 'string') {
        return assert.equal(text, holder);
      } else {
        throw "Can't test a text of type " + (typeof text) + ".";
      }
    })();
    omniboxText = null;
    alertText = null;
    return out;
  };

  expectSuggestionFor = function(text, output) {
    changeInput(text);
    return assertOmni(output);
  };

  expectResponseFor = function(text, output) {
    enterInput(text);
    return assertAlert(output);
  };

  expectNoResponseFor = function(text) {
    enterInput(text);
    return assertNoOutput();
  };

  assertFocus = function(winId, tabId) {
    if (winId !== focusedWindowId) {
      assert.fail("Expected window " + winId + " to be focused, was window " + focusedWindowId);
    }
    if (tabId !== windows[focusedWindowId].activeTabId) {
      return assert.fail("Excpected tab " + tabId + " to be focused, was tab " + windows[focusedWindowId].activeTabId);
    }
  };

  context("Commands", should("initialize", function() {
    var def, win2;
    reset();
    assert.equal('function', typeof TabShepherd);
    assert.equal('object', typeof ts);
    assert.isTrue(inputChanged != null);
    assert.isTrue(inputEntered != null);
    win2 = windows[2];
    assert.equal('goodbye', win2.name);
    def = ts.getDefinition(win2.name);
    assert.isTrue(def != null);
    return assert.equal('blue', def.patterns[0]);
  }));

  context("makeText", should("assemble strings", function() {
    reset();
    assert.equal('a string', ts.makeText('a string'));
    assert.equal("window \"2\"'s color is bluegreen", ts.makeText("window %w's color is %s", 2, 'bluegreen'));
    assert.equal("color is blue|green", ts.makeText("color is %s", 'blue|green'));
    assert.equal('color is /blue|green/', ts.makeText("color is %p", 'blue|green'));
    return assert.equal("color is 'bluegreen'", ts.makeText("color is %p", 'bluegreen'));
  }));

  context("Commands", should("show help", function() {
    changeInput('help', suggest);
    return assertOmni(/^Possible commands:/);
  }));

  context("Commands", should("show help on a command", function() {
    var cmd, name, ref, results;
    ref = ts.commands();
    results = [];
    for (name in ref) {
      if (!hasProp.call(ref, name)) continue;
      cmd = ref[name];
      changeInput("help " + name, suggest);
      if ((cmd.alias == null) && name !== 'help') {
        results.push(assertOmni(name + ": " + cmd.desc));
      } else {
        results.push(void 0);
      }
    }
    return results;
  }));

  context("name", should("handle command", function() {
    reset();
    expectSuggestionFor('name', 'Enter a name for this window.');
    expectResponseFor('name', 'No name provided.');
    expectSuggestionFor('name foo', 'Press enter to name this window "foo".');
    expectNoResponseFor('name foo');
    assert.equal('foo', windows[focusedWindowId].name);
    assert.isTrue(defs['foo'] != null);
    assert.equal('foo', defs['foo'].name);
    expectSuggestionFor('name ', 'Enter a new name for this window (currently named "foo").');
    expectSuggestionFor('name blah', 'Press enter to change window name from "foo" to "blah".');
    enterInput('name blah');
    assert.equal('blah', windows[focusedWindowId].name);
    assert.isTrue(defs['blah'] != null);
    assert.isFalse(defs['foo'] != null);
    return assert.equal('blah', defs['blah'].name);
  }));

  context("defs", should("handle command", function() {
    reset();
    expectSuggestionFor('defs', 'Press enter to list the window definitions.');
    expectResponseFor('defs', "Named windows:\n\ngoodbye (window 2)");
    enterInput('name hi');
    return expectResponseFor('defs', "Named windows:\n\ngoodbye (window 2)\nhi (window 1)");
  }));

  context("new", should("handle command", function() {
    reset();
    expectSuggestionFor('name foo', 'Press enter to name this window "foo".');
    expectSuggestionFor('new', 'Enter a name for the new window.');
    expectSuggestionFor('new yes', 'Press enter to open a new window and name it "yes".');
    expectSuggestionFor('new yes okay', 'Press enter to open a new window named "yes" and assign it the pattern \'okay\'.');
    expectSuggestionFor('new yes hello|goodbye', 'Press enter to open a new window named "yes" and assign it the pattern /hello|goodbye/.');
    expectNoResponseFor('new yes okay');
    assert.equal('yes', windows[focusedWindowId].name);
    withSavedDef('yes', function(def) {
      assert.isTrue(def != null);
      assert.equal('yes', def.name);
      return assert.equal('okay', def.patterns[0]);
    });
    return expectSuggestionFor('new yes', 'There is already a window named "yes".');
  }));

  context("find", should("handle command", function() {
    reset();
    expectSuggestionFor('find', 'Enter a pattern to find a tab.');
    expectResponseFor('find', 'Enter a pattern to find a tab.');
    expectSuggestionFor('find things', "Press enter to focus the first of 3 tabs matching 'things'.");
    expectNoResponseFor('find things');
    assertFocus(1, 3);
    expectSuggestionFor('find really', "Press enter to focus the tab matching 'really' in window \"hello\".");
    expectNoResponseFor('find really');
    assertFocus(1, 4);
    expectSuggestionFor('find sweet|bitter', "Press enter to focus the first of 2 tabs matching /sweet|bitter/.");
    expectNoResponseFor('find sweet|bitter');
    assertFocus(1, 3);
    expectSuggestionFor('find s[aeiou]{2}r', "Press enter to focus the tab matching /s[aeiou]{2}r/ in window \"goodbye\".");
    expectNoResponseFor('find s[aeiou]{2}r');
    assertFocus(2, 5);
    expectSuggestionFor('find umami', "No matching tabs found for 'umami'.");
    expectResponseFor('find umami', "No matching tabs found for 'umami'.");
    assertFocus(2, 5);
    expectSuggestionFor('find um.*mi', "No matching tabs found for /um.*mi/.");
    expectResponseFor('find um.*mi', "No matching tabs found for /um.*mi/.");
    assertFocus(2, 5);
    return assert.equal(2, Object.keys(windows).length);
  }));

  Tests.run();

}).call(this);
